services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - NODE_ENV=production
      - N8N_PATH=/n8n/
      - WEBHOOK_URL=http://localhost:8080/n8n/
    volumes:
      - ./data/n8n:/home/node/.n8n
      - ../dist:/home/node/.n8n/custom
    ports:
      - 5678:5678
    depends_on:
      build:
        condition: service_completed_successfully

  build:
    image: gplane/pnpm:node20-alpine
    volumes:
      - ..:/build
    working_dir: /build
    command: ["run", "build-docker"]

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data

  whoami:
    image: traefik/whoami
    restart: always

  caddy:
    image: caddy:alpine
    restart: always
    environment:
      - WEBHOOK_ID=aa1e42ef-7492-4235-9f22-e3c007358d15
    ports:
      - 8080:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
