services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.77.3
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./data/n8n:/home/node/.n8n
    ports:
      - 8081:5678

  redis:
    image: redis/redis-stack:latest
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/redis:/data
    ports:
      - 8082:8001

  grist:
    image: gristlabs/grist-oss
    restart: always
    volumes:
      - ./data/grist:/persist
    environment:
      - GRIST_SESSION_SECRET=invent-a-secret-here
      - GRIST_DEFAULT_EMAIL=admin@example.com
      - GRIST_SANDBOX_FLAVOR=gvisor
      - APP_HOME_URL=http://localhost:8080
      - GRIST_SINGLE_ORG=example-com
      - COOKIE_MAX_AGE=604800000
      - GRIST_HIDE_UI_ELEMENTS=helpCenter,billing,templates,createSite,multiSite,multiAccounts,sendToDrive,tutorials,supportGrist
      - GRIST_PAGE_TITLE_SUFFIX=
      - GRIST_WIDGET_LIST_URL="https://github.com/gristlabs/grist-widget/releases/download/latest/manifest.json"
      - ALLOWED_WEBHOOK_DOMAINS=n8n:5678
      - GRIST_FORWARD_AUTH_HEADER=X-Forwarded-User
      - GRIST_FORWARD_AUTH_LOGOUT_PATH=/_auth/logout
      - REDIS_URL=redis://redis:6379
      # - GRIST_DOCS_MINIO_ACCESS_KEY=
      # - GRIST_DOCS_MINIO_SECRET_KEY=
      # - GRIST_DOCS_MINIO_ENDPOINT=
      # - GRIST_DOCS_MINIO_PORT=
      # - GRIST_DOCS_MINIO_USE_SSL=
      # - GRIST_DOCS_MINIO_BUCKET=
    depends_on:
      redis:
        condition: service_healthy
  caddy:
    image: caddy:alpine
    restart: always
    environment:
      - WEBHOOK_ID=b45467ee-fe7e-4479-a25e-601b17eaf6a0
    ports:
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
