services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    user: root
    restart: always
    environment:
      - NODE_ENV=production
      - N8N_PATH=/n8n/
    volumes:
      - ./data/n8n:/root/.n8n
      - ../dist:/root/.n8n/custom/HttpForwardAuth
    depends_on:
      build:
        condition: service_completed_successfully

  build:
    image: gplane/pnpm:node20-alpine
    volumes:
      - ..:/build
    working_dir: /build
    command: ["run", "build-docker"]

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data

  whoami:
    image: traefik/whoami
    restart: always

  caddy:
    image: caddy:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
